import { createRoot } from "react-dom/client";
import App from "./app/App.tsx";
import "./styles/index.css";

// ✅ PWA: Register service worker (generated by vite-plugin-pwa)
import { registerSW } from "virtual:pwa-register";

const updateSW = registerSW({
  // Called when a new version of the app is available
  onNeedRefresh() {
    // You can show a toast/dialog here instead of confirm()
    if (confirm("A new version of the app is available. Reload to update?")) {
      updateSW(true);
    }
  },
  // Called when the app is ready to work offline
  onOfflineReady() {
    console.log("✅ App is ready to work offline!");
    // Optionally show a toast: "App is ready to use offline"
  },
  onRegisteredSW(swUrl, r) {
    console.log(`Service Worker registered at: ${swUrl}`, r);
  },
  onRegisterError(error) {
    console.error("Service Worker registration error:", error);
  },
});

createRoot(document.getElementById("root")!).render(<App />);